# vim:ft=ansible:
- hosts: localhost
  vars:
    dotfiles_dir: ~/dotfiles/
    
    symlinks:
      xinitrc:
        from: xorg/.xinitrc
        to: .xinitrc
      xprofile:
        from: xorg/xprofile
        to: .profile
      userdir:
        from: user-dirs.dirs
        to: .config/user-dirs.dirs
      rofi:
        from: rofi
        to: .config/rofi
      alacritty:
        from: alacritty
        to: .config/alacritty
      vim:
        from: vim 
        to: .config/nvim
      zsh:
        from: zsh/zshrc 
        to: .zshrc
      mpv:
        from: mpv 
        to: .config/mpv
      sway:
        from: sway
        to: .config/sway
      wal:
        from: wal
        to: .config/wal
      polybar:
        from: polybar
        to: .config/polybar
      dunst:
        from: dunst
        to: .config/dunst

    flatpakpackages:
      - com.discordapp.Discord
      - com.valvesoftware.Steam
      - com.skype.Client
      - com.spotify.Client

    pippackages:
      - pywal
      - i3ipc
      - neovim

    enabledservices:
      - acpid
      - alsa
      - chronyd
      - dbus
      - nanoklogd
      - socklog-unix
      - udevd
      - ufw
      - uuidd
      - dhcpcd
      - elogind

    neededpackages:
      - socklog-void
      - xorg-minimal
      - xrdb 
      - xrandr 
      - xprop 
      - xinit 
      - libXft
      - libX11
      - xf86-video-amdgpu
      - ImageMagick
      - xdg-desktop-portal 
      - xdg-user-dirs 
      - xdg-utils
      - xset
      - setxkbmap
      - maim
      - xdotool
      - i3-gaps 
      - i3lock 
      - font-awesome5
      - font-fira-otf 
      - font-fira-ttf 
      - font-firacode
      - noto-fonts-cjk 
      - noto-fonts-emoji 
      - noto-fonts-ttf
      - acpi 
      - sysstat 
      - lm_sensors 
      - lshw 
      - curl
      - zsh
      - xclip
      - exa 
      - fzf
      - cargo
      - ripgrep
      - htop 
      - neovim 
      - wget 
      - rsync
      - ranger
      - flatpak
      - firejail
      - redshift 
      - dmenu 
      - feh 
      - rofi
      - sxiv
      - alacritty
      - firefox
      - ffmpeg
      - gst-plugins-bad1 gst-plugins-good1
      - mpv
      - nodejs 
      - clang 
      - boost 
      - git
      - cmake 
      - python3 
      - python3-pip 
      - gcc 
      - fontconfig-devel 
      - pkg-config 
      - python3-devel 
      - p7zip
      - yarn
      - ccls
      - alsa-utils
      - pulseaudio
      - pavucontrol
      - ponymix 
      - fcitx
      - fcitx-configtool
      - libfcitx-gtk 
      - libfcitx-gtk3 
      - libfcitx-qt 
      - libfcitx-qt5
      - lxappearance
      - jq
      - chrony
      - ufw
      - docker
      - starship
      - polybar
      - picom
      - composer
      - php
      - php-devel
      - php-intl
      - php-mysql
      - php-sqlite
      - php-xsl
      - unzip
      - alsa-plugins-pulseaudio
      - elogind
      - terraform

  tasks:
    - name: Update package repos
      become: true
      xbps: update_cache=yes upgrade=yes
    - name: Install packages
      become: true
      xbps: name={{ item }} state=latest
      with_items: "{{ neededpackages }}"
    
    - name: Install pip packages
      pip:
        name: "{{ item }}"
        extra_args: --user
      loop: "{{ pippackages }}"
    
    - name: lm_sensors
      become: true
      command: sensors-detect --auto
      
    - name: User management
      become: true
      user:
        append: yes
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
        groups:
          - wheel
          - audio
          - video
          - cdrom
          - kvm
          - input
          - users
          - pulse-access
          - socklog
          - docker
    
    - name: Dircolors
      shell: dircolors -p > ~/.dircolors
      args:
        creates: ~/.dircolors
    
    - name: Runit Services
      become: true
      runit:
        state: started
        name: "{{ item }}"
        enabled: yes
      loop: "{{ enabledservices }}"
    
    - name: Add flathub repo
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user
    
    - name: Flatpak Installations
      flatpak: 
        name: "{{ item }}"
        state: present
        method: user
      loop: "{{ flatpakpackages }}"

    - name: Flatpak Discord Override
      command:
        cmd: flatpak override --user --filesystem=~/Drive/Downloads --filesystem=/proc com.discordapp.Discord
        creates: ~/.local/share/flatpak/overrides/com.discordapp.Discord

    - name: Flatpak Steam Override
      command:
        cmd: flatpak override --user --filesystem=~/Drive com.valvesoftware.Steam
        creates: ~/.local/share/flatpak/overrides/com.valvesoftware.Steam

    - name: Flatpak Skype Override
      command:
        cmd: flatpak override --user --filesystem=~/Drive/Downloads --filesystem=~/Documents com.skype.Client
        creates: ~/.local/share/flatpak/overrides/com.skype.Client

    - name: create config dir
      file:
        path: ~/.config
        state: directory

    - name: Symlink the dotfiles
      file:
        src: "{{ dotfiles_dir }}{{ item.value.from }}"
        dest: "~/{{ item.value.to }}"
        state: link
      loop: "{{ lookup('dict', symlinks) }}"
