export DOTFILES=$HOME/dotfiles

source $DOTFILES/zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search



# Load the theme.
antigen theme lambda

# Tell Antigen that you're done.
antigen apply

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=4'

source $DOTFILES/zsh/aliase.zsh
source $DOTFILES/zsh/environment.zsh
source $DOTFILES/zsh/functions.zsh
. "/home/effi/.acme.sh/acme.sh.env"
